import type { NextPage } from 'next';
import Head from 'next/head';
import Container from '../../components/Container';

const Blog: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Blog | Aryan Pathania</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>This is a navbar</p>

      <main>
        <h1>Welcome to my Blog.</h1>
      </main>

      <footer>Aryan</footer>
    </Container>
  );
};

export default Blog;
